-- USE DB_PHP_QUIZZ;

CREATE TABLE IF NOT EXISTS USER (
    idUser INT(11) NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    admin BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (idUser)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS TYPEQUIZZ (
    idType INT(11) NOT NULL AUTO_INCREMENT,
    typeQ VARCHAR(255) NOT NULL,
    PRIMARY KEY (idType)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS TYPEQUESTION (
    idTypeQst INT(11) NOT NULL AUTO_INCREMENT,
    typeQst VARCHAR(255) NOT NULL, -- radio, checkbox, text, ...
    PRIMARY KEY (idTypeQst)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS QUIZZ (
    idQuizz INT(11) NOT NULL AUTO_INCREMENT,
    titre_quizz VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    type_id INT(11) NOT NULL,
    user_id INT(11) NOT NULL,
    PRIMARY KEY (idQuizz),
    FOREIGN KEY (user_id) REFERENCES USER(idUser),
    FOREIGN KEY (type_id) REFERENCES TYPEQUIZZ(idType)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS QUESTION (
    idQst INT(11) NOT NULL AUTO_INCREMENT,
    labelQst VARCHAR(255) NOT NULL,
    typeQst_id INT(11) NOT NULL,
    quizz_id INT(11) NOT NULL,
    PRIMARY KEY (idQst),
    FOREIGN KEY (quizz_id) REFERENCES QUIZZ(idQuizz),
    FOREIGN KEY (typeQst_id) REFERENCES TYPEQUESTION(idTypeQst)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS CHOIX (
    idChoix INT(11) NOT NULL AUTO_INCREMENT,
    labelChoix VARCHAR(255) NOT NULL,
    question_id INT(11) NOT NULL,
    bonneReponse BOOLEAN NOT NULL,
    PRIMARY KEY (idChoix),
    FOREIGN KEY (question_id) REFERENCES QUESTION(idQst)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS SCORE (
    idScore INT(11) NOT NULL AUTO_INCREMENT,
    score INT(11) NOT NULL,
    user_id INT(11) NOT NULL,
    quizz_id INT(11) NOT NULL,
    PRIMARY KEY (idScore),
    FOREIGN KEY (user_id) REFERENCES USER(idUser),
    FOREIGN KEY (quizz_id) REFERENCES QUIZZ(idQuizz)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

