-- drop all tables 

DROP TABLE IF EXISTS SCORE;
DROP TABLE IF EXISTS CHOIX;
DROP TABLE IF EXISTS QUESTION;
DROP TABLE IF EXISTS TYPEQUESTION;
DROP TABLE IF EXISTS QUIZZ;
DROP TABLE IF EXISTS TYPEQUIZZ;
DROP TABLE IF EXISTS USER;